# Default values for cvocr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

cognitive_service_api_key: dummy
cognitive_service_api_billing_endpoint: "https://northeurope.api.cognitive.microsoft.com/"

image:
  repository: containerpreview.azurecr.io/microsoft/cognitive-services-ocr
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: cogsvc-acr-secret

ports:
  containerPort: 5000

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |2
             sub_filter '"url":"/swagger/v1/swagger.json"' '"url":"/cvocr/swagger/v1/swagger.json"';
             sub_filter 'href="/swagger">' 'href="/cvocr/swagger">';
             sub_filter_once on;
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: localhost
      paths: [
        "/cvocr(/|$)(.*)"        
      ]
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
